import "@solana/bridge-adapter-react-ui/index.css";
import * as BridgeAdapterReact from "@solana/bridge-adapter-react";
import * as React from "react";
import * as WalletAdapters from "@solana/wallet-adapter-wallets";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { BridgeAdapter } from "@solana/bridge-adapter-react-ui";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const solanaRpcUrl = process.env.NEXT_PUBLIC_SOLANA_RPC_URL;

const walletConnectProjectId =
  process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID;

export default function Home({
  title = "Bridge Adapter Demo",
}: {
  title: string;
}) {
  if (!walletConnectProjectId || walletConnectProjectId.length === 0) {
    throw new Error("Define `walletConnectProjectId`");
  }

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const wallets = React.useMemo(
    () =>
      typeof globalThis.window === "undefined"
        ? []
        : [
            new WalletAdapters.SolflareWalletAdapter(),
            new WalletAdapters.CoinbaseWalletAdapter(),
          ],
    [],
  );

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const evmSettings = React.useMemo(
    () => ({
      coinbaseWalletSettings: {
        appName: title ?? "",
      },
      walletConnectProjectId,
    }),
    [title],
  );

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [error, setError] = React.useState<Error | undefined>();

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <BridgeAdapterReact.SolanaWalletProvider
          autoConnect={false}
          onError={(e: Error) => setError(e)}
          wallets={wallets}
        >
          <BridgeAdapterReact.EvmWalletProvider
            coinbaseWalletSettings={evmSettings.coinbaseWalletSettings}
            walletConnectProjectId={evmSettings.walletConnectProjectId}
          >
            <BridgeAdapterReact.BridgeAdapterProvider
              bridgeAdapterSettings={{
                allow: ["deBridge", "wormhole"],
              }}
              error={error}
              settings={{
                solana: { solanaRpcUrl },
              }}
            >
              <BridgeAdapter className={styles.inner} title={title} />
            </BridgeAdapterReact.BridgeAdapterProvider>
          </BridgeAdapterReact.EvmWalletProvider>
        </BridgeAdapterReact.SolanaWalletProvider>
      </main>
    </>
  );
}
